MAINTAINERS: Remove people that against the LGBT+
torvalds/linux pull request #1031
Opened 2024-10-28 02:49 UTC by Ashonyer

Oh, Linus Joker

2024-10-28 02:59 UTC, System233 approved these changes
LGTM

2024-10-28 03:28 UTC, AkemiKami201 commented
LGTV

2024-10-28 06:42 UTC, Fido6 approved these changes
LGTM

2024-10-28 14:36 UTC, zby-c commented
THATS FOR SURE

2024-10-29 03:03 UTC, liangguifeng commented
LGTM

2024-10-29 09:32 UTC, michael-eddy commented
this pr is not freedom!

2024-11-19 04:47 UTC, FukudaBQ commented
LGBT: Linus Giga Bi**h Torvalds

2024-11-24 18:29 UTC, raffleberry requested changes
uno reverse

2025-06-02 02:29 UTC, blhmr commented
You’re a moron

2025-06-02 02:50 UTC, okineadev commented
> You’re a moron

https://github.com/user-attachments/assets/10cf3d0b-1d6a-44f9-8f89-f43a4dd3e629

2025-09-22 17:08 UTC, closed without merging