Update tsacct.c
torvalds/linux pull request #1075
Opened 2024-11-08 02:31 UTC by abhinandanlahori

Optimize acct_update_integrals by replacing local_irq_save with a more fine-grained spinlock (tsk->mm->page_table_lock) to reduce locking overhead. This minimizes the time interrupts are disabled while still ensuring the integrity of the accounting data.

2024-11-08 15:09 UTC, swicherwich approved these changes
Looks good from my side.

2024-11-17 02:22 UTC, axhuoga1 commented
这有些看不懂，但写的还行

2024-11-20 06:55 UTC, mysterion requested changes
please add benchmarks/tests regarding the changes.

2025-03-02 16:00 UTC, lucaosti approved these changes

2025-09-22 17:05 UTC, closed without merging