Uncrustify
torvalds/linux pull request #825
Opened 2024-03-22 21:54 UTC by Lurgrid

2024-03-23 06:40 UTC, danemadsen approved these changes
lgtm

2024-04-04 19:59 UTC, WackyModer commented
still seems a bit crusty

2024-04-13 23:10 UTC, jsk-official approved these changes
lgtm

2024-04-16 07:15 UTC, Adrian8115 requested changes
Too many changes

2024-04-22 18:58 UTC, Lurgrid commented
> Too many changes

"Change is the only constant in life." - Heraclitus

2024-05-01 08:52 UTC, KwiatekMiki approved these changes
looks good

2024-05-07 23:13 UTC, gato001k1 commented
damm it doesn't even load.

2025-06-10 05:49 UTC, closed without merging