pr_debug for vhci_hcd unlink->seqnum and urb->status
torvalds/linux pull request #841
Opened 2024-04-14 10:16 UTC by frostworx

While using usbip as client, the journal is flooded with

```
Apr 14 12:12:28 mini kernel: vhci_hcd: unlink->seqnum 158446
Apr 14 12:12:28 mini kernel: vhci_hcd: urb->status -131
```
messages, because `pr_info` is used.

With this PR, I'd like to suggest using `pr_debug` instead,
because the info most likely is only interesting for debugging.

2024-04-14 10:18 UTC, dukie commented
stop

On Sun, Apr 14, 2024, 19:17 frostworx ***@***.***> wrote:

> While using usbip as client, the journal is flooded with
>
> Apr 14 12:12:28 mini kernel: vhci_hcd: unlink->seqnum 158446
> Apr 14 12:12:28 mini kernel: vhci_hcd: urb->status -131
>
> messages, because pr_info is used.
>
> With this PR, I'd like to suggest using pr_debug instead,
> because the info most likely is only interesting for debugging.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/torvalds/linux/pull/841
> Commit Summary
>
>    - d34449a
>    <https://github.com/torvalds/linux/pull/841/commits/d34449ae8a9dacbdc90e454c602ef7929e1afe25>
>    pr_debug for vhci_hcd unlink->seqnum and urb->status
>
> File Changes
>
> (1 file <https://github.com/torvalds/linux/pull/841/files>)
>
>    - *M* drivers/usb/usbip/vhci_rx.c
>    <https://github.com/torvalds/linux/pull/841/files#diff-29f260d94345a10e5e83e3876fea0c8aa07d28a10c9704084b62852e46a8db03>
>    (4)
>
> Patch Links:
>
>    - https://github.com/torvalds/linux/pull/841.patch
>    - https://github.com/torvalds/linux/pull/841.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/torvalds/linux/pull/841>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIXYJVU65TLFJDCND6A67TY5JJUDAVCNFSM6AAAAABGGDFJW2VHI2DSMVQWIX3LMV43ASLTON2WKOZSGI2DEMBYGI3TEOA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-04-14 10:27 UTC, frostworx commented
pardon?

2024-04-22 06:50 UTC, ricky6672 approved these changes

2024-04-22 06:53 UTC, ricky6672 requested changes
- - Kslle_@_

2024-07-14 10:50 UTC, frostworx commented
of course the patch is not significant, but still, it would be nice to have it upstream _(especially on weak systems)_

2025-09-22 17:55 UTC, closed without merging