Update README
torvalds/linux pull request #897
Opened 2024-06-20 14:00 UTC by guilhermelinosp

2024-06-20 16:04 UTC, LaCapitainerie requested changes
You litteraly add a space and ask for a PR..
Rejected.

2024-06-21 10:49 UTC, gmehdiev commented
This is a good pull request.
Confirmed.

2024-06-23 02:53 UTC, gabriel-logan reviewed
Nem fudendo...

2024-06-23 03:38 UTC, coldmayo commented
Wow, thanks for solving such a pressing issue! We really needed help with this and you were the only dev in the whole world who knew how to fix it. You're the chosen one.

2024-06-23 03:51 UTC, brenoepics commented
LGTM!

2024-06-23 13:14 UTC, douglasfdev commented
![](https://cdn.meutimao.com.br/_upload/forum/2024/02/18/absolute_cinema_97.jpeg)

2024-06-23 15:34 UTC, MrsRina commented
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

2024-06-23 15:44 UTC, P4nda-K1ng commented
Why are these emails almost always shitposts

2024-06-25 09:47 UTC, LaCapitainerie requested changes
Delete this PR, mail anoy me and the PR is not funny

2024-06-25 09:47 UTC, LaCapitainerie commented on README
> +the problems which may result by upgrading your kernel.
Just a fucking space

2024-06-26 16:09 UTC, Real-Glitch commented
ban this guy

2024-06-26 18:10 UTC, xXDeonoXx commented
you are a shame for us Brazilians lol

2024-06-26 18:19 UTC, closed without merging

2024-06-26 18:21 UTC, guilhermelinosp commented
> [xXDeonoXx](/xXDeonoXx)

cuida da sua vida aee pokedex

2024-06-26 19:53 UTC, xXDeonoXx commented
cuidado gente, o juninho incompetente ficou brabo KKKKKKKKKKKKK

Em qua., 26 de jun. de 2024 às 15:21, Guilherme (лино) Lino <
***@***.***> escreveu:

> xXDeonoXx <http:///xXDeonoXx>
>
> cuida da sua vida aee pokedex
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/torvalds/linux/pull/897#issuecomment-2192370985>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKYTUS44CEETSNAGCKQSCP3ZJMBCVAVCNFSM6AAAAABJUBCB4WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJSGM3TAOJYGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-06-26 21:33 UTC, MrsRina commented
Totally disrespectful with Linux development community.