/////////////''''''''''\ggggggggggggggggggggggggggggfffffffffffffffff…
torvalds/linux pull request #956
Opened 2024-09-17 00:12 UTC by noahdossan

…fffffffffffffffd

g';flllllllllllllllllllllllllllllld'g;dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'[;hj

\h'jgggggggggghglf

\\\'\d'f Sticky keys have been disabled

2024-09-17 02:48 UTC, noahdossan commented
Found my keyboard on the floor, sorry.

2024-09-17 02:48 UTC, closed without merging

2024-09-17 03:41 UTC, leofloripa reviewed
@kadamski

2024-09-17 03:42 UTC, leofloripa commented
@sugi

2024-11-08 10:01 UTC, michael-eddy commented
rexbr7t8h978yt68879ty87hyyinmyf cxdruik,l;.ggfd rcazwsedrftfvgbyhnjkm,  rtfyujinkm 4drtfgvbhjn m

2025-03-09 23:34 UTC, vk8a8 commented
peak

2025-03-12 02:35 UTC, leofloripa requested changes
unnecessary change

2025-03-12 02:36 UTC, leofloripa commented on README
> +llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllLinux kernel
Kerneeellllllllllllllllllll